server:
    port: 10002

zuul:
  routes:
    api:
      path: /api/**
      url: http://localhost:10001
      stripPrefix: false
    uaa:
      path: /uaa/me
      url: http://localhost:10000
      stripPrefix: false